---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[openstack::default]
      - recipe[openstack::_example_swift]
    attributes:
